name: Tflint
on:
  pull_request:


jobs:
  tflint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - account_billing_alert
          - account_cloudtrail
          - alternate_contacts
          - cf_basic_auth
          - eks
          - iam_sso
          - RDSOSMetrics_loggroup
    steps:
    - uses: makandra/github-actions/tflint@main
      with:
        path: modules/${{ matrix.path }}
